<div>
    <input type="text" id="amount" placeholder="Enter donation amount here.....">
    <button id="btn-razorpay">Pay with Razorpay</button>
</div>
<div class="modal-container">
    <div class="modal">
        <div class="close">×</div>
        <div id='response'></div>
    </div>
</div>

<style>
    .modal-container {
        display: none;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: 99999;
        opacity: 0;
        white-space: nowrap;
        background: rgba(0, 0, 0, 0.4);
        transition: 0.25s opacity;
        -webkit-transition: 0.25s opacity;
        text-align: center;
        font-family: sans-serif;
    }
    .modal-container.shown {
        opacity: 1;
    }
    .modal-container.shown .modal {
        transform: none;
        -webkit-transform: none;
        -moz-transform: none;
        transition: 0.3s cubic-bezier(.3, 1.5, .7,1) transform, 0.25s opacity;
    }
    .modal-container:after {
        content: '';
        display: inline-block;
        vertical-align: middle;
        height: 100%;
        vertical-align: middle;
        display: inline-block;
    }
    .modal {
        text-align: left;
        background: #fff;
        padding: 30px 20px;
        white-space: normal;
        transform: translateY(30px) scale(0.9);
        transition: 0.25s ease-in;
        vertical-align: middle;
        display: inline-block;
        max-width: 500px;
        position: relative;
        border-radius: 4px;
    }
    .close {
        cursor: pointer;
        position: absolute;
        right: 0px;
        top: -4px;
        width: 36px;
        text-align: center;
        line-height: 36px;
        color: rgba(0, 0, 0, 0.6);
        border-radius: 0 4px 4px 0;
        font-size: 24px;
        transition: 0.2s;
    }
    .close:hover {
        color: #333;
    }
</style>

<script src="#liveurl#"></script>

<form name='razorpayform' id="paymentform" action="#redirectUrl#" method="POST">
    <input type="hidden" name="razorpay_payment_id" id="razorpay_payment_id">
    <input type="hidden" name="razorpay_signature"  id="razorpay_signature" >
</form>

<script>
jQuery(document).ready(function($){
    function showModal(response) {
        $('#response').html(response);
        $('html, body').css('overflow', 'hidden');
        $('.modal-container').show().prop('offsetHeight');
        $('.modal-container').addClass('shown');
    }

    function hideModal() {
        $('html, body').css('overflow', '');
        $('.modal-container').removeClass('shown');
        setTimeout(function() {
            $('.modal-container').hide();
        }, 300)
        document.getElementById("btn-razorpay").disabled = false;
    }

    $('.close').click(hideModal);

    // global method
    function createOrder(){
        amount = $('#amount').val();
        $.ajax({
            url: "#redirectUrl#?action=create_order&page_id=#pageID#&amount=" + amount.toString(),
            type: 'GET',
            success: function(order) {   
                if (order.hasOwnProperty('error')){
                    showModal(order['error']);
                }
                else{
                    order.handler = function(payment){
                        $('#razorpay_payment_id').val(payment.razorpay_payment_id);
                        $('#razorpay_signature').val(payment.razorpay_signature);

                        var form_data = $('form').serializeArray();
                        
                        $.ajax({
                            url: "#redirectUrl#", 
                            data: form_data,
                            type: 'POST',
                            success: function(response){
                                showModal(response);
                            }
                        });
                    };
                }

                // On dismissing the popup, enable the button again
                order.modal = {
                    ondismiss: function(){
                        document.getElementById("btn-razorpay").disabled = false;
                    }
                };

                // After order is created, open checkout
                openCheckout(order);
            }
        })
    }

    // global method
    function openCheckout(order) {
        var razorpayCheckout = new Razorpay(order);
        razorpayCheckout.open();
    }

    function disableRzpButton(){
        document.getElementById("btn-razorpay").disabled = true;
    }


    function addEvent(element, evnt, funct){
        if (element.attachEvent)
            return element.attachEvent('on' + evnt, funct);
        else
            return element.addEventListener(evnt, funct, false);
    }

    addEvent(document.getElementById("btn-razorpay"), 'click', createOrder);
    addEvent(document.getElementById("btn-razorpay"), 'click', disableRzpButton);
})
</script>
