<div>
    <button id="btn-razorpay">Pay with Razorpay</button>
</div>
<div class="modal-container">
    <div class="modal">
        <div class="close">×</div>
        <div id='response'></div>
    </div>
</div>

<style>
    .modal-container {
        display: none;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: 99999;
        opacity: 0;
        white-space: nowrap;
        background: rgba(0, 0, 0, 0.4);
        transition: 0.25s opacity;
        -webkit-transition: 0.25s opacity;
        text-align: center;
        font-family: sans-serif;
    }
    .modal-container.shown {
        opacity: 1;
    }
    .modal-container.shown .modal {
        transform: none;
        -webkit-transform: none;
        -moz-transform: none;
        transition: 0.3s cubic-bezier(.3, 1.5, .7,1) transform, 0.25s opacity;
    }
    .modal-container:after {
        content: '';
        display: inline-block;
        vertical-align: middle;
        height: 100%;
        vertical-align: middle;
        display: inline-block;
    }
    .modal {
        text-align: left;
        background: #fff;
        padding: 30px 20px;
        white-space: normal;
        transform: translateY(30px) scale(0.9);
        transition: 0.25s ease-in;
        vertical-align: middle;
        display: inline-block;
        max-width: 500px;
        position: relative;
        border-radius: 4px;
    }
    .close {
        cursor: pointer;
        position: absolute;
        right: 0px;
        top: -4px;
        width: 36px;
        text-align: center;
        line-height: 36px;
        color: rgba(0, 0, 0, 0.6);
        border-radius: 0 4px 4px 0;
        font-size: 24px;
        transition: 0.2s;
    }
    .close:hover {
        color: #333;
    }
</style>

<script src="#liveurl#"></script>

<form name='razorpayform' id="paymentform" action="#redirectUrl#" method="POST">
    <input type="hidden" name="order_amount" value="#amount#">
    <input type="hidden" name="razorpay_payment_id" id="razorpay_payment_id">
    <input type="hidden" name="razorpay_signature"  id="razorpay_signature" >
</form>

<script>
jQuery(document).ready(function( $ ){
    function showModal(response) {
        $('#response').html(response);
        $('html, body').css('overflow', 'hidden');
        $('.modal-container').show().prop('offsetHeight');
        $('.modal-container').addClass('shown');
    }
    function hideModal() {
        $('html, body').css('overflow', '');
        $('.modal-container').removeClass('shown');
        setTimeout(function() {
            $('.modal-container').hide();
        }, 300)
    }
    $('.close').click(hideModal);

    // global method
    function createOrder()
    {
        $.ajax({
            url: "#redirectUrl#" + "?action=create_order&page_id=" + "#pageID#",
            type: 'GET',
            success: function(order) 
            {  
                rzp_order = JSON.parse(order);
                
                rzp_order.handler = function(payment)
                {
                    document.getElementById('razorpay_payment_id').value = payment.razorpay_payment_id;
                    document.getElementById('razorpay_signature').value = payment.razorpay_signature;

                    var form_data = $('form').serializeArray();
                    
                    $.ajax({
                        url: "#redirectUrl#", 
                        data: form_data,
                        type: 'POST',
                        success: function(response){
                            showModal(response);
                        }
                    });
                };

                // After order is created, open checkout
                openCheckout(rzp_order);
            }
        })
    }

    // global method
    function openCheckout(rzp_order) 
    {
        var razorpayCheckout = new Razorpay(rzp_order);
        razorpayCheckout.open();
    }

    document.getElementById("btn-razorpay").onclick = function()
    {
        createOrder();
    }
})
</script>
